services:
  backend_app:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    command: >
      sh -c "pipenv run flask run --host=0.0.0.0 --port=5000"
    env_file:
      - .env

  frontend_app:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run dev -- --host"
    env_file:
      - .env
