services:
  backend_app:
    build: ./backend
    container_name: flask_app
    ports:
      - "5001:5001"
    command: >
      sh -c "pipenv run flask run --host=0.0.0.0 --port=5001"
    env_file:
      - .env

  frontend_app:
    build: ./frontend
    container_name: react_app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm run dev -- --host"
    env_file:
      - .env
