services:
  backend_app:
    build: ./backend
    container_name: express_app
    ports:
      - "5000:5000"
    command: >
      sh -c "npm install && npm run dev"
    env_file:
      - .env

  frontend_app:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run dev -- --host"
    env_file:
      - .env
